package se.ju23.typespeeder.gameLogic;

public enum Status {
    OK, EXIT, ACTIVE_IN_GAME, NO_USER_FOUND, VERIFIED, CONTINUANCE, IN_GAME_SETTINGS, PLAYING_GAME, CHANGING_ALIAS, CHANGING_PASSWORD, CHANGING_USERNAME, SETTING_LANGUAGE
}
